INFO     App_Run_Test:base_page.py:13 Waiting for element: [name="firstName"]
ERROR    App_Run_Test:base_page.py:19 Element '[name="firstName"]' not found within 5000ms. Exception: Locator.wait_for: Timeout 5000ms exceeded.
Call log:
  - waiting for locator("[name=\"firstName\"]") to be visible

ERROR    App_Run_Test:ui_actions.py:28 Error while getting element: [name="firstName"]. Exception: Element '[name="firstName"]' not found within 5000ms.
INFO     App_Run_Test:base_page.py:13 Waiting for element: [name="lastName"]
ERROR    App_Run_Test:base_page.py:19 Element '[name="lastName"]' not found within 5000ms. Exception: Locator.wait_for: Timeout 5000ms exceeded.
Call log:
  - waiting for locator("[name=\"lastName\"]") to be visible

ERROR    App_Run_Test:ui_actions.py:28 Error while getting element: [name="lastName"]. Exception: Element '[name="lastName"]' not found within 5000ms.